"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "cs" | "en"

type Translations = {
  [key in Language]: {
    [key: string]: string
  }
}

const translations: Translations = {
  cs: {
    home: "Domů",
    tryIt: "Vyzkoušej",
    dndDiceRoller: "DnD kostky",
    notepad: "Poznámkový blok",
    languageSwitcher: "Přepínač jazyků",
    montyHall: "Monty Hall simulátor",
    coinflip: "Hod mincí",
    rockPaperScissors: "Kámen nůžky papír",
    clickSpeedTest: "Test rychlosti klikání",
    startupIdea: "Startup nápad",
    uselessButton: "Zbytečné tlačítko",
    textConverter: "Převod textu",
    typingTest: "Test psaní",
    insultGenerator: "Generátor urážek",
    roll: "Hodit",
    save: "Uložit",
    clear: "Vymazat",
    copyAll: "Zkopírovat vše",
    paste: "Vložit",
    switchLanguage: "Přepnout jazyk",
    chooseADoor: "Vyberte dveře",
    switchDoor: "Změnit výběr",
    keepDoor: "Ponechat výběr",
    reset: "Resetovat",
    youWon: "Vyhráli jste!",
    youLost: "Prohráli jste!",
    door: "Dveře",
    selectDiceType: "Vyberte typ kostky",
    numberOfDice: "Počet kostek",
    result: "Výsledek",
    yourNotes: "Vaše poznámky",
    language: "Jazyk",
    cards: "Karty",
    notepadDesc: "Napiš si co chceš",
    montyHallDesc: "Klasický paradox",
    coinflipDesc: "Férová nebo nefér mince",
    rockPaperScissorsDesc: "AI se učí tvé vzorce",
    clickSpeedTestDesc: "Jak rychle klikáš?",
    startupIdeaDesc: "Bizarní nápady na startup",
    uselessButtonDesc: "Možná něco udělá",
    textConverterDesc: "Šifrování textu",
    typingTestDesc: "Rychlé psaní náročných vět",
    insultGeneratorDesc: "Roztomile urážlivé hlášky",
    montyHallExplanation:
      "Monty Hall problém je slavný pravděpodobnostní paradox založený na televizní soutěži. Máte na výběr ze tří dveří, za jedněmi je auto, za dvěma kozy. Po výběru dveří moderátor otevře jedny z nevybraných dveří s kozou. Pak máte možnost změnit svůj výběr. Matematicky je lepší změnit výběr - šance na výhru se zvýší z 1/3 na 2/3.",
    fairness: "Férnost",
    fair: "Férová",
    unfair: "Nefér",
    flip: "Hodit",
    heads: "Panna",
    tails: "Orel",
    rock: "Kámen",
    paper: "Papír",
    scissors: "Nůžky",
    youChose: "Vybrali jste",
    aiChose: "AI vybralo",
    tie: "Remíza",
    wins: "vítězství",
    losses: "prohry",
    ties: "remízy",
    clicksPerSecond: "kliků za sekundu",
    startTest: "Začít test",
    timeLeft: "Zbývající čas",
    generateIdea: "Generovat nápad",
    clickMe: "Klikni na mě",
    convertText: "Převést text",
    inputText: "Zadej text",
    startTyping: "Začít psaní",
    wpm: "slov za minutu",
    accuracy: "přesnost",
    generateInsult: "Generovat urážku",
    typingSentences: [
      "Šel žluťoučký kůň do Vídně",
      "Příliš žluťoučký kůň úpěl ďábelské ódy",
      "Čtvrthrst zrn",
      "Smrž pln skvrn zvlhl z mlh",
      "Strč prst skrz krk",
    ],
    clickMessages: [
      "Wow, to bylo rychlé!",
      "Jsi klikací stroj!",
      "Tvoje prsty jsou v ohni!",
      "Klik klik klik!",
      "Jsi rychlejší než světlo!",
      "Myš se bojí!",
      "Tlačítko prosí o milost!",
      "Jsi klikací legenda!",
    ],
    startupIdeas: [
      "Airbnb pro domácí mazlíčky",
      "Uber pro doručování objetí",
      "Netflix pro sledování trávy jak roste",
      "Tinder pro párování ponožek",
      "Instagram pro kameny",
      "Spotify pro zvuky ticha",
      "Amazon pro prodej vzduchu",
      "LinkedIn pro mrtvé",
      "TikTok pro rostliny",
      "YouTube pro sledování barvy jak schne",
    ],
    uselessMessages: [
      "Nic se nestalo",
      "Stále nic",
      "Možná příště",
      "Zkus to znovu",
      "Nope",
      "Ani náhodou",
      "Ještě ne",
      "Zkus štěstí jinde",
    ],
    insults: [
      "Jsi tak roztomilý, že by tě i medvěd pohladil",
      "Máš mozek jako počítač... z roku 1995",
      "Jsi jako WiFi heslo - těžko zapamatovatelný",
      "Tvoje inteligence je jako tvoje vlasy - řídká",
      "Jsi tak pomalý, že by tě předběhl šnek na valiu",
      "Máš charisma jako mokrá ponožka",
    ],
    conversionType: "Typ převodu",
    morse: "Morseovka",
    caesar: "Caesarova šifra",
    atbash: "Atbash",
    shift: "Posun",
  },
  en: {
    home: "Home",
    tryIt: "Try it out",
    dndDiceRoller: "DnD Dice Roller",
    notepad: "Notepad",
    languageSwitcher: "Language Switcher",
    montyHall: "Monty Hall Simulator",
    coinflip: "Coinflip",
    rockPaperScissors: "Rock Paper Scissors",
    clickSpeedTest: "Click Speed Test",
    startupIdea: "Startup Idea",
    uselessButton: "Useless Button",
    textConverter: "Text Converter",
    typingTest: "Typing Test",
    insultGenerator: "Insult Generator",
    roll: "Roll",
    save: "Save",
    clear: "Clear",
    copyAll: "Copy All",
    paste: "Paste",
    switchLanguage: "Switch Language",
    chooseADoor: "Choose a door",
    switchDoor: "Switch door",
    keepDoor: "Keep door",
    reset: "Reset",
    youWon: "You won!",
    youLost: "You lost!",
    door: "Door",
    selectDiceType: "Select dice type",
    numberOfDice: "Number of dice",
    result: "Result",
    yourNotes: "Your notes",
    language: "Language",
    cards: "Cards",
    notepadDesc: "Write whatever you want",
    montyHallDesc: "Classic paradox",
    coinflipDesc: "Fair or unfair coin",
    rockPaperScissorsDesc: "AI learns your patterns",
    clickSpeedTestDesc: "How fast can you click?",
    startupIdeaDesc: "Bizarre startup ideas",
    uselessButtonDesc: "Maybe it does something",
    textConverterDesc: "Text encryption",
    typingTestDesc: "Fast typing of difficult sentences",
    insultGeneratorDesc: "Cutely offensive messages",
    montyHallExplanation:
      "The Monty Hall problem is a famous probability puzzle based on a game show. You choose from three doors, one has a car, two have goats. After your choice, the host opens one of the remaining doors with a goat. Then you can switch your choice. Mathematically, it's better to switch - your winning chance increases from 1/3 to 2/3.",
    fairness: "Fairness",
    fair: "Fair",
    unfair: "Unfair",
    flip: "Flip",
    heads: "Heads",
    tails: "Tails",
    rock: "Rock",
    paper: "Paper",
    scissors: "Scissors",
    youChose: "You chose",
    aiChose: "AI chose",
    tie: "Tie",
    wins: "wins",
    losses: "losses",
    ties: "ties",
    clicksPerSecond: "clicks per second",
    startTest: "Start Test",
    timeLeft: "Time left",
    generateIdea: "Generate Idea",
    clickMe: "Click Me",
    convertText: "Convert Text",
    inputText: "Enter text",
    startTyping: "Start Typing",
    wpm: "words per minute",
    accuracy: "accuracy",
    generateInsult: "Generate Insult",
    typingSentences: [
      "The quick brown fox jumps over the lazy dog",
      "Pack my box with five dozen liquor jugs",
      "How vexingly quick daft zebras jump",
      "Bright vixens jump; dozy fowl quack",
      "Sphinx of black quartz, judge my vow",
    ],
    clickMessages: [
      "Wow, that was fast!",
      "You're a clicking machine!",
      "Your fingers are on fire!",
      "Click click click!",
      "You're faster than light!",
      "The mouse is scared!",
      "The button begs for mercy!",
      "You're a clicking legend!",
    ],
    startupIdeas: [
      "Airbnb for pets",
      "Uber for hug delivery",
      "Netflix for watching grass grow",
      "Tinder for matching socks",
      "Instagram for rocks",
      "Spotify for silence sounds",
      "Amazon for selling air",
      "LinkedIn for the dead",
      "TikTok for plants",
      "YouTube for watching paint dry",
    ],
    uselessMessages: [
      "Nothing happened",
      "Still nothing",
      "Maybe next time",
      "Try again",
      "Nope",
      "Not a chance",
      "Not yet",
      "Try your luck elsewhere",
    ],
    insults: [
      "You're so cute, even a bear would pet you",
      "You have a brain like a computer... from 1995",
      "You're like a WiFi password - hard to remember",
      "Your intelligence is like your hair - sparse",
      "You're so slow, a snail on valium would pass you",
      "You have the charisma of a wet sock",
    ],
    conversionType: "Conversion Type",
    morse: "Morse Code",
    caesar: "Caesar Cipher",
    atbash: "Atbash",
    shift: "Shift",
  },
}

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("cs")

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
